<?php

namespace ContainerDRdZeJA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xyy4xWkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xyy4xWk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xyy4xWk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::addBien' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController::annulerFacturation' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController::biens' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController::editBien' => ['privates', '.service_locator.elki6F.', 'get_ServiceLocator_Elki6F_Service', true],
            'App\\Controller\\AdminController::facturations' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController::reservations' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\BienController::list' => ['privates', '.service_locator.lwXeAq6', 'get_ServiceLocator_LwXeAq6Service', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\OwnerController::ownerReservations' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\ReservationController::index' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController::register' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AdminController:addBien' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController:annulerFacturation' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController:biens' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController:editBien' => ['privates', '.service_locator.elki6F.', 'get_ServiceLocator_Elki6F_Service', true],
            'App\\Controller\\AdminController:facturations' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController:reservations' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\BienController:list' => ['privates', '.service_locator.lwXeAq6', 'get_ServiceLocator_LwXeAq6Service', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\OwnerController:ownerReservations' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\ReservationController:index' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController:register' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AdminController::addBien' => '?',
            'App\\Controller\\AdminController::annulerFacturation' => '?',
            'App\\Controller\\AdminController::biens' => '?',
            'App\\Controller\\AdminController::editBien' => '?',
            'App\\Controller\\AdminController::facturations' => '?',
            'App\\Controller\\AdminController::reservations' => '?',
            'App\\Controller\\BienController::list' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\OwnerController::ownerReservations' => '?',
            'App\\Controller\\ReservationController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::register' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:addBien' => '?',
            'App\\Controller\\AdminController:annulerFacturation' => '?',
            'App\\Controller\\AdminController:biens' => '?',
            'App\\Controller\\AdminController:editBien' => '?',
            'App\\Controller\\AdminController:facturations' => '?',
            'App\\Controller\\AdminController:reservations' => '?',
            'App\\Controller\\BienController:list' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\OwnerController:ownerReservations' => '?',
            'App\\Controller\\ReservationController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:register' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
