<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDRdZeJA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDRdZeJA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDRdZeJA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDRdZeJA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDRdZeJA\App_KernelDevDebugContainer([
    'container.build_hash' => 'DRdZeJA',
    'container.build_id' => '44b556a3',
    'container.build_time' => 1696446410,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDRdZeJA');
